import React from 'react';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';

import Modal from '../Modal';
import { fetchQuizzes } from '../../actions';
import '../../styles/quizList.css'
import history from '../../history';

class QuizList extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            showQuizCreate: false
        }
    }
    componentDidMount() {
        this.props.fetchQuizzes();
    }

    quizStart(id) {
        history.push(`/quiz/start/${id}`)
    }

    // QUIZZES LIST
    renderList() {
        if (Object.keys(this.props.quizzes).length !== 0) {
            return this.props.quizzes.map((quiz, index) => {
                return (
                    <div className="four wide column setCard" key={quiz._id} onClick={() => this.quizStart(quiz._id)}>
                        <div className="ui simple icon bottom right floated dropdown button" onClick={(e) => e.stopPropagation()}>
                            <i className="ellipsis vertical icon"></i>
                            <div className="menu" >
                                <Link to={`/quiz/edit/${quiz._id}`} className="item">
                                    <i className="edit icon"></i>
                                    Edit
                                    </Link>
                                <Link to={`/quiz/delete/${quiz._id}`} className="item">
                                    <i className="trash alternate icon"></i>
                                    Delete
                                    </Link>
                            </div>
                        </div>
                        <h3 className="setCard_title noselect" id={quiz.quizName} >{quiz.quizName} </h3>
                    </div>
                );
            });
        } 
    }

    // CREATE QUIZ CHOICES MODAL
    toggleCreateModal() {
        this.setState(state => ({ showQuizCreate: !state.showQuizCreate }))
    }

    renderModalContent() {
        return (
            <div className="ui two cards">
                <Link to={"/quiz/create/auto"} >
                    <div className="ui link card" onClick={this.toggleCreateModal.bind(this)}>
                        <div className="content">
                            <div className="header">
                                Automatic
                            </div>
                            <div className="ui form">
                                <div className="field">
                                    <label>Questions</label>
                                    <textarea rows="3" disabled></textarea>
                                </div>
                                <div className="field">
                                    <label>Answers</label>
                                    <textarea rows="3" disabled></textarea>
                                </div>
                            </div>
                        </div>
                        <div className="extra content">
                            <div className="description">
                                Automatic is as simple as copy pasting as options will automatically generated by using the provided answers.
                            <br />
                            Minimum questions with answer: 4.
                        </div>
                        </div>
                    </div>
                </Link>
                <Link to="/quiz/create/manual">
                    <div className="ui link card" onClick={this.toggleCreateModal.bind(this)}>
                        <div className="content">
                            <div className="header">
                                Manual
                         </div>
                            <div className="ui card">
                                <div className="content">
                                    <label>Question 1: </label>
                                    <div className="field">
                                        <input
                                            autoComplete="off"
                                            size="32"
                                            disabled
                                        />
                                    </div>
                                    <label>Options:</label>
                                    <div className="ui internally celled grid">
                                        <div className="row">
                                            <div className="eight wide column">
                                                <div className="field">
                                                    <input
                                                        autoComplete="off"
                                                        size="10"
                                                        disabled
                                                    />
                                                </div>
                                            </div>
                                            <div className="eight wide column">
                                                <div className="field">
                                                    <input
                                                        autoComplete="off"
                                                        size="10"
                                                        disabled
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="eight wide column">
                                                <div className="field">
                                                    <input
                                                        autoComplete="off"
                                                        size="10"
                                                        disabled
                                                    />
                                                </div>
                                            </div>
                                            <div className="eight wide column">
                                                <div className="field">
                                                    <input
                                                        autoComplete="off"
                                                        size="10"
                                                        disabled
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="extra content">
                            <div className="description">
                                Manual lets you put your own options on each question for a more personalized quiz.
                            <br />
                            No minimum questions!
                        </div>
                        </div>
                    </div>
                </Link>
            </div>
        )
    }

    renderActions() {
        return (
            <div className="ui right floated buttons">
                <button type="button" onClick={this.toggleCreateModal.bind(this)} className="ui button">Cancel</button>;
            </div>
        )
    }

    renderQuizCreate() {
        return <Modal
            title="Choose how you create your quiz!"
            visibility={this.state.showQuizCreate}
            content={this.renderModalContent()}
            actions={this.renderActions()}
            onDismiss={this.toggleCreateModal.bind(this)}
        />
    }

    render() {
        return (
            <div className="quizList-container">
                {this.renderQuizCreate()}
                <div className="ui container">
                    <h2 className="ui header" id="quizListheader">
                        <i className="book icon"></i>
                        <div className="content">
                            Quiz List
                    <div className="sub header">Start or Create a Quiz</div>
                        </div>
                    </h2>
                    <div className="ui grid quizSet-container">
                        {this.renderList()}
                        <div onClick={this.toggleCreateModal.bind(this)} className="four wide column setCard">
                            <div className="ui container">
                                <i className="green plus circle big icon"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
};

const mapStateToProps = state => {
    return {
        quizzes: Object.values(state.quiz)
    }
};

export default connect(mapStateToProps, { fetchQuizzes })(QuizList);