export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const CLEAR_QUESTION = 'CLEAR_QUESTION';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_QUIZ = 'CREATE_QUIZ';
export const FETCH_QUIZZES = 'FETCH_QUIZZES';
export const FETCH_QUIZ = 'FETCH_QUIZ';
export const FETCH_SHUFFLED_QUIZ = 'FETCH_SHUFFLED_QUIZ';
export const EDIT_QUIZ = 'EDIT_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';

export const SET_ERROR = "SET_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";

/**
 *
 *
export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_ERROR = 'ADD_QUESTION_ERROR';

export const REMOVE_QUESTION_REQUEST = 'REMOVE_QUESTION_REQUEST';
export const REMOVE_QUESTION_SUCCESS = 'REMOVE_QUESTION_SUCCESS';
export const REMOVE_QUESTION_ERROR = 'REMOVE_QUESTION_ERROR';

export const CLEAR_QUESTION_REQUEST = 'CLEAR_QUESTION_REQUEST';
export const CLEAR_QUESTION_SUCCESS = 'CLEAR_QUESTION_SUCCESS';
export const CLEAR_QUESTION_ERROR = 'CLEAR_QUESTION_ERROR';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const CREATE_QUIZ_REQUEST = 'CREATE_QUIZ_REQUEST';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
export const CREATE_QUIZ_ERROR = 'CREATE_QUIZ_ERROR';

export const FETCH_QUIZZES_REQUEST = 'FETCH_QUIZZES_REQUEST';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR';

export const FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR';

export const FETCH_SHUFFLED_QUIZ_REQUEST = 'FETCH_SHUFFLED_QUIZ_REQUEST';
export const FETCH_SHUFFLED_QUIZ_SUCCESS = 'FETCH_SHUFFLED_QUIZ_SUCCESS';
export const FETCH_SHUFFLED_QUIZ_ERROR = 'FETCH_SHUFFLED_QUIZ_ERROR';

export const EDIT_QUIZ_REQUEST = 'EDIT_QUIZ_REQUEST';
export const EDIT_QUIZ_SUCCESS = 'EDIT_QUIZ_SUCCESS';
export const EDIT_QUIZ_ERROR = 'EDIT_QUIZ_ERROR';

export const DELETE_QUIZ_REQUEST = 'DELETE_QUIZ_REQUEST';
export const DELETE_QUIZ_SUCCESS = 'DELETE_QUIZ_SUCCESS';
export const DELETE_QUIZ_ERROR = 'DELETE_QUIZ_ERROR';
 */